import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderNavbar } from "@/components/HeaderNavbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Start  with boxe club ASCM" />
        <title>ASCM ton club de boxe!</title>
      </head>
      <UserProvider>
        <body className={inter.className}>
          <div className="sticky top-0 w-full h-full bg-black overflow-hidden z-10">
            <HeaderNavbar />
          </div>
          <div>{children}</div>
        </body>
      </UserProvider>
    </html>
  );
}
